'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';
import { User, Lock, Mail, ChevronLeft, Eye, EyeOff, Loader2, Phone, GraduationCap } from 'lucide-react';
import { fetchAPI } from '../../../lib/api';

export default function StudentRegisterPage() {
    const router = useRouter();
    const [formData, setFormData] = useState({
        name: '',
        phone: '',
        parentPhone: '',
        governorate: 'القاهرة',
        password: '',
        confirmPassword: '',
        gradeLevel: 'SECONDARY_1'
    });

    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState('');
    const [showPassword, setShowPassword] = useState(false);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsLoading(true);
        setError('');

        if (formData.password !== formData.confirmPassword) {
            setError("كلمات المرور غير متطابقة");
            setIsLoading(false);
            return;
        }

        try {
            const autoGeneratedEmail = `student_${formData.phone}@shater.com`;

            // Extract subdomain if running on a tenant subdomain
            let subdomain = '';
            if (typeof window !== 'undefined') {
                const hostname = window.location.hostname;
                if (hostname.includes('elshate.com') && !hostname.startsWith('www')) {
                    subdomain = hostname.split('.')[0];
                } else if (hostname.includes('localhost') && hostname.split('.').length > 1) {
                    subdomain = hostname.split('.')[0];
                }
            }

            await fetchAPI('/auth/register', {
                method: 'POST',
                body: JSON.stringify({
                    name: formData.name,
                    email: autoGeneratedEmail,
                    phone: formData.phone,
                    parentPhone: formData.parentPhone,
                    governorate: formData.governorate,
                    password: formData.password,
                    role: 'STUDENT',
                    gradeLevel: formData.gradeLevel,
                    subdomain: subdomain || undefined
                }),
            });

            // Auto login or redirect to login
            router.push('/login?registered=true');
        } catch (err: any) {
            setError(err.message || "فشل إنشاء الحساب");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="min-h-screen grid grid-cols-1 lg:grid-cols-2 bg-slate-50 dark:bg-slate-950" dir="rtl">
            {/* Visual Side */}
            <div className="hidden lg:flex flex-col justify-center items-center bg-gradient-to-br from-blue-600 to-indigo-700 text-white p-12 relative overflow-hidden">
                <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=2070&auto=format&fit=crop')] bg-cover bg-center opacity-20"></div>
                <div className="relative z-10 max-w-lg text-center">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.2 }}
                    >
                        <GraduationCap className="w-20 h-20 mx-auto mb-6 opacity-80" />
                        <h1 className="text-4xl font-bold mb-4">ابدأ رحلتم التعليمية</h1>
                        <p className="text-xl text-blue-100 mb-8">
                            الوصول إلى أفضل المعلمين والمحتوى التعليمي المتميز في مكان واحد.
                        </p>
                    </motion.div>
                </div>
            </div>

            {/* Form Side */}
            <div className="flex items-center justify-center p-8 overflow-y-auto h-screen">
                <motion.div
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="w-full max-w-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl shadow-xl p-8"
                >
                    <div className="text-center mb-8">
                        <h2 className="text-3xl font-bold text-slate-800 dark:text-white">
                            حساب طالب جديد
                        </h2>
                        <p className="text-slate-500 dark:text-slate-400 mt-2">سجل بياناتك للدخول إلى المنصة</p>
                    </div>

                    <form onSubmit={handleSubmit} className="space-y-5">
                        {error && (
                            <div className="p-4 bg-red-50 dark:bg-red-900/20 text-red-600 border border-red-200 dark:border-red-800 rounded-xl text-sm font-medium">
                                {error}
                            </div>
                        )}

                        <div>
                            <label className="block text-sm font-medium mb-1.5 text-right">الاسم الكامل</label>
                            <div className="relative">
                                <User className="absolute right-3 top-3 text-slate-400 w-5 h-5" />
                                <input
                                    type="text"
                                    required
                                    className="w-full pr-10 pl-4 py-2.5 bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 rounded-xl border focus:ring-2 focus:ring-indigo-500 outline-none text-right"
                                    placeholder="اسم الطالب"
                                    value={formData.name}
                                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-1.5 text-right">رقم هاتف الطالب</label>
                            <div className="relative">
                                <Phone className="absolute right-3 top-3 text-slate-400 w-5 h-5" />
                                <input
                                    type="tel"
                                    required
                                    className="w-full pr-10 pl-4 py-2.5 bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 rounded-xl border focus:ring-2 focus:ring-indigo-500 outline-none text-right"
                                    placeholder="01xxxxxxxxx"
                                    value={formData.phone}
                                    onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-1.5 text-right">رقم هاتف ولي الأمر</label>
                            <div className="relative">
                                <Phone className="absolute right-3 top-3 text-slate-400 w-5 h-5" />
                                <input
                                    type="tel"
                                    required
                                    className="w-full pr-10 pl-4 py-2.5 bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 rounded-xl border focus:ring-2 focus:ring-indigo-500 outline-none text-right"
                                    placeholder="01xxxxxxxxx"
                                    value={formData.parentPhone}
                                    onChange={(e) => setFormData({ ...formData, parentPhone: e.target.value })}
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-1.5 text-right">المحافظة</label>
                            <div className="relative">
                                <select
                                    required
                                    className="w-full px-4 py-2.5 bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 rounded-xl border focus:ring-2 focus:ring-indigo-500 outline-none text-right appearance-none"
                                    value={formData.governorate}
                                    onChange={(e) => setFormData({ ...formData, governorate: e.target.value })}
                                >
                                    {[
                                        "القاهرة", "الجيزة", "الإسكندرية", "الدقهلية", "الشرقية", "المنوفية", "القليوبية", "البحيرة", "الغربية", "بورسعيد",
                                        "دمياط", "الإسماعيلية", "السويس", "كفر الشيخ", "الفيوم", "بني سويف", "مطروح", "شمال سيناء", "جنوب سيناء",
                                        "المنيا", "أسيوط", "سوهاج", "قنا", "البحر الأحمر", "الأقصر", "أسوان", "الواحات", "الوادي الجديد"
                                    ].map((gov) => (
                                        <option key={gov} value={gov}>{gov}</option>
                                    ))}
                                </select>
                            </div>
                        </div>



                        <div>
                            <label className="block text-sm font-medium mb-1.5 text-right">المرحلة الدراسية</label>
                            <div className="relative">
                                <GraduationCap className="absolute right-3 top-3 text-slate-400 w-5 h-5" />
                                <select
                                    required
                                    className="w-full pr-10 pl-4 py-2.5 bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 rounded-xl border focus:ring-2 focus:ring-indigo-500 outline-none text-right appearance-none"
                                    value={formData.gradeLevel}
                                    onChange={(e) => setFormData({ ...formData, gradeLevel: e.target.value })}
                                >
                                    <optgroup label="المرحلة الإعدادية">
                                        <option value="PREPARATORY_1">الأول الإعدادي</option>
                                        <option value="PREPARATORY_2">الثاني الإعدادي</option>
                                        <option value="PREPARATORY_3">الثالث الإعدادي</option>
                                    </optgroup>
                                    <optgroup label="المرحلة الثانوية">
                                        <option value="SECONDARY_1">الأول الثانوي</option>
                                        <option value="SECONDARY_2">الثاني الثانوي</option>
                                        <option value="SECONDARY_3">الثالث الثانوي</option>
                                    </optgroup>
                                </select>
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-1.5 text-right">كلمة المرور</label>
                            <div className="relative">
                                <Lock className="absolute right-3 top-3 text-slate-400 w-5 h-5" />
                                <input
                                    type={showPassword ? "text" : "password"}
                                    required
                                    className="w-full pr-10 pl-12 py-2.5 bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 rounded-xl border focus:ring-2 focus:ring-indigo-500 outline-none text-right"
                                    placeholder="••••••••"
                                    value={formData.password}
                                    onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                                />
                                <button
                                    type="button"
                                    onClick={() => setShowPassword(!showPassword)}
                                    className="absolute left-3 top-3 text-slate-400 hover:text-slate-600"
                                >
                                    {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                                </button>
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-1.5 text-right">تأكيد كلمة المرور</label>
                            <div className="relative">
                                <Lock className="absolute right-3 top-3 text-slate-400 w-5 h-5" />
                                <input
                                    type="password"
                                    required
                                    className="w-full pr-10 pl-4 py-2.5 bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 rounded-xl border focus:ring-2 focus:ring-indigo-500 outline-none text-right"
                                    placeholder="••••••••"
                                    value={formData.confirmPassword}
                                    onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
                                />
                            </div>
                        </div>

                        <button
                            type="submit"
                            disabled={isLoading}
                            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg shadow-blue-600/20 disabled:opacity-70 disabled:cursor-not-allowed mt-4"
                        >
                            {isLoading ? (
                                <>
                                    <Loader2 className="w-5 h-5 animate-spin" />
                                    جاري إنشاء الحساب...
                                </>
                            ) : (
                                <>
                                    إنشاء حساب جديد <ChevronLeft size={20} />
                                </>
                            )}
                        </button>
                    </form>

                    <div className="mt-8 text-center text-sm space-y-2">
                        <div className="text-slate-500">
                            <span>لديك حساب بالفعل؟ </span>
                            <Link href="/login" className="text-blue-600 font-bold hover:underline">
                                تسجيل الدخول
                            </Link>
                        </div>
                    </div>

                </motion.div>
            </div>
        </div>
    );
}
